title: Shreeya
description: Researcher in Algorithms and Machine Learning
author: Shreeya
remote_theme: daattali/beautiful-jekyll

# Socials
social-network-links:
  email: shreeyac@iitb.ac.in
  github: shreeyaac
  
  linkedin: shreeyac
  twitter: not yet

# Navbar â€” we'll keep only minimal links; sidebar handles main nav
navbar-links:
  Home: "/"
  Courses: "courses"
  Projects: "projects"
  Research Stuff: "research"
  CV: "cv"

plugins:
  - jekyll-feed

markdown: kramdown
